### ISSUE TITLE
How to Update forked repos?

### ISSUE THREAD

**Issue by samsulmaarif** [za/debian-handbook_id-ID#5]
mas za, gimana cara mengupdate repo yang saya fork dari debian-id/debian-handbook_id-ID agar bisa terupdate dengan upstreamnya.

Terima Kasih.

**Comment by samsulmaarif** [comment]
Oh, solusinya sudah saya temukan di sini : http://share.ez.no/blogs/virgil-ciobanu/how-to-syncronize-your-github-fork-with-original-repository

Mohon maaf, sepertinya issue ini sebenarnya tidak terlalu perlu :P

**Comment by za** [comment]
Eh gpp. Kan yang lain bisa belajar juga jadinya.
